name: template
description: "A new Flutter project."
version: 1.0.0+2

environment:
  sdk: ^3.6.2
  # flutter: "3.29.2" 
  # Current stable version
  # Dart SDK version should be compatible with the Flutter SDK version.
  # For example, if you are using Flutter 3.29.2, the Dart SDK version should be compatible with it.
  # You can check the compatible Dart SDK version for your Flutter version in the Flutter documentation.
  # https://docs.flutter.dev/development/tools/sdk/releases

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  flutter_svg: ^2.0.17
  delayed_display: ^2.0.0
  flutter_riverpod: ^2.6.1
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4
  flutter_pin_code_fields: ^2.2.0
  pinput: ^5.0.1
  intl: ^0.20.2
  permission_handler: ^12.0.0
  flutter_tts: ^4.2.2
  avatar_glow: ^3.0.1
  retrofit: ^4.4.2
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  dartz: ^0.10.1
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  toastification: ^3.0.2
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  pretty_dio_logger: ^1.4.0
  talker_dio_logger: ^4.7.1
  jumping_dot: ^0.0.7
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9

flutter:

  uses-material-design: true

  # To add assets to your apgit remote set-url origin git@github.com:FarhanAli-98/template.gitplication, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Regular.ttf
